name: rumour
description: "Make audio-first RPG's with no code."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  backstreets_widgets: ^0.31.1
  cupertino_icons: ^1.0.8
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  file_picker: ^8.1.7
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.37.1
  flutter_riverpod: ^2.6.1
  flutter_soloud: ^2.1.7
  jinja: ^0.6.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  drift_dev: ^2.23.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
