name: rumour_player
description: "A package for playing rumour games."
version: 0.0.1
repository:  https://github.com/chrisnorman7/rumour
publish_to: none
environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.32.0
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.37.4
  flutter_lints: ^5.0.0
  flutter_riverpod: ^2.6.1
  flutter_soloud: ^2.1.7
  path: ^1.9.1
  riverpod_annotation: ^2.6.1
  rumour_backend:
    path: ../rumour_backend
  time: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
